name: coop_foundation_models
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pip:
    - absl-py==1.3.0
    - addict==2.4.0
    - antlr4-python3-runtime==4.9.3
    - anyio==4.0.0
    - appdirs==1.4.4
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.3.0
    - asttokens==2.4.0
    - async-lru==2.0.4
    - attrs==23.1.0
    - babel==2.13.0
    - backcall==0.2.0
    - beautifulsoup4==4.12.2
    - black==21.4b2
    - bleach==6.0.0
    - cachetools==5.2.1
    - charset-normalizer==2.1.1
    - click==8.1.3
    - git+https://github.com/openai/CLIP.git
    - cloudpickle==2.2.0
    - comm==0.1.4
    - contourpy==1.0.6
    - cycler==0.11.0
    - cython==0.29.33
    - debugpy==1.8.0
    - decorator==5.1.1
    - defusedxml==0.7.1
    - exceptiongroup==1.1.3
    - executing==2.0.0
    - fastjsonschema==2.18.1
    - filelock==3.12.0
    - fonttools==4.38.0
    - fqdn==1.5.1
    - fsspec==2023.5.0
    - ftfy==6.1.1
    - future==0.18.2
    - fvcore==0.1.5.post20221221
    - google-auth==2.16.0
    - google-auth-oauthlib==0.4.6
    - groundingdino-py==0.4.0
    - grpcio==1.51.1
    - huggingface-hub==0.14.1
    - hydra-core==1.3.1
    - importlib-metadata==6.6.0
    - importlib-resources==5.10.2
    - iopath==0.1.9
    - ipykernel==6.25.2
    - ipython==8.12.3
    - isoduration==20.11.0
    - jedi==0.19.1
    - jinja2==3.1.2
    - joblib==1.3.2
    - json5==0.9.14
    - jsonpointer==2.4
    - jsonschema==4.19.1
    - jsonschema-specifications==2023.7.1
    - jupyter-client==8.3.1
    - jupyter-core==5.3.2
    - jupyter-events==0.7.0
    - jupyter-lsp==2.2.0
    - jupyter-server==2.7.3
    - jupyter-server-terminals==0.4.4
    - jupyterlab==4.0.6
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.25.0
    - kiwisolver==1.4.4
    - lvis==0.5.3
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.6.2
    - matplotlib-inline==0.1.6
    - mistune==3.0.2
    - mypy-extensions==0.4.3
    - nbclient==0.8.0
    - nbconvert==7.9.0
    - nbformat==5.9.2
    - nest-asyncio==1.5.8
    - notebook-shim==0.2.3
    - oauthlib==3.2.2
    - omegaconf==2.3.0
    - open-clip-torch==2.23.0
    - opencv-python==4.7.0.68
    - overrides==7.4.0
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pathspec==0.10.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pkgutil-resolve-name==1.3.10
    - platformdirs==3.6.0
    - portalocker==2.6.0
    - prometheus-client==0.17.1
    - prompt-toolkit==3.0.39
    - protobuf==3.20.3
    - psutil==5.9.5
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycocotools==2.0.6
    - pydot==1.4.2
    - pygments==2.16.1
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - python-json-logger==2.0.7
    - pytz==2023.3.post1
    - pyzmq==25.1.1
    - referencing==0.30.2
    - regex==2022.10.31
    - requests==2.31.0
    - requests-oauthlib==1.3.1
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rpds-py==0.10.3
    - rsa==4.9
    - safetensors==0.3.1
    - scikit-learn==1.3.1
    - scipy==1.10.0
    - segment-anything==1.0
    - send2trash==1.8.2
    - sentencepiece==0.1.99
    - setuptools==59.5.0
    - shapely==2.0.2
    - sniffio==1.3.0
    - soupsieve==2.5
    - stack-data==0.6.3
    - supervision==0.6.0
    - tabulate==0.9.0
    - tensorboard==2.11.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - termcolor==2.2.0
    - terminado==0.17.1
    - threadpoolctl==3.2.0
    - timm==0.9.8
    - tinycss2==1.2.1
    - tokenizers==0.13.3
    - toml==0.10.2
    - tomli==2.0.1
    - tornado==6.3.3
    - tqdm==4.64.1
    - traitlets==5.11.2
    - transformers==4.30.2
    - types-python-dateutil==2.8.19.14
    - uri-template==1.3.0
    - urllib3==1.26.13
    - wcwidth==0.2.6
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.6.3
    - werkzeug==2.2.2
    - yacs==0.1.8
    - yapf==0.40.0
    - zipp==3.11.0
    - yaml==0.2.5
    - gmp==6.2.1
    - cryptography==39.0.1
    - pyopenssl==23.0.0
    - libdeflate==1.7
    - tifffile==2020.10.1
    - libuv==1.43.0
    - jpeg==9e
    - lcms2==2.12
    - bzip2==1.0.8
    - _libgcc_mutex==0.1
    - _openmp_mutex==5.1
    - blas==1.0
    - brotlipy==0.7.0
    - ca-certificates==2023.05.30
    - certifi==2023.5.7
    - cffi==1.15.1
    - cudatoolkit==11.3.1
    - cytoolz==0.12.0
    - dask-core==2022.2.1
    - ffmpeg==4.3
    - freetype==2.10.4
    - gnutls==3.6.13
    - idna==3.4
    - imageio==2.31.1
    - intel-openmp==2021.4.0
    - jbig==2.1
    - lame==3.100
    - ld_impl_linux-64==2.38
    - lerc==2.2.1
    - libffi==3.4.2
    - libgcc-ng==11.2.0
    - libgfortran-ng==11.2.0
    - libgfortran5==11.2.0
    - libgomp==11.2.0
    - libiconv==1.17
    - libpng==1.6.37
    - libstdcxx-ng==11.2.0
    - libtiff==4.3.0
    - libwebp-base==1.2.2
    - locket==1.0.0
    - lz4-c==1.9.3
    - mkl==2021.4.0
    - mkl-service==2.4.0
    - mkl_fft==1.3.1
    - mkl_random==1.2.2
    - ncurses==6.3
    - nettle==3.6
    - networkx==2.8.4
    - numpy==1.23.5
    - numpy-base==1.23.5
    - olefile==0.46
    - openh264==2.1.1
    - openjpeg==2.4.0
    - openssl==1.1.1u
    - packaging==23.0
    - partd==1.2.0
    - pillow==8.3.2
    - pip==22.3.1
    - pooch==1.4.0
    - pycparser==2.21
    - pysocks==1.7.1
    - python==3.8.15
    - python_abi==3.8
    - pytorch==1.10.1
    - pytorch-mutex==1.0
    - pywavelets==1.4.1
    - pyyaml==6.0
    - readline==8.2
    - scikit-image==0.19.3
    - six==1.16.0
    - sqlite==3.40.1
    - tk==8.6.12
    - toolz==0.12.0
    - torchaudio==0.10.1
    - torchvision==0.11.2
    - typing_extensions==4.4.0
    - wheel==0.37.1
    - xz==5.2.8
    - zlib==1.2.13
    - zstd==1.5.0
